services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TaskDb123!"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

  GerenciadorTarefasAPI:
   image: gerenciador_tarefas_api
   build:
     context: .
     dockerfile: GerenciadorTarefas.Api/Dockerfile
   depends_on:
    - sqlserver
   ports:
    - 8080:80

volumes:
  sql_data:
    driver: local